# Generated by Django 4.0.3 on 2022-03-24 19:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_habilidades_alter_personas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='cv',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
