# Generated by Django 4.0.3 on 2022-03-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_personas_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='personas'),
        ),
    ]
