# Generated by Django 4.0.3 on 2022-03-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_personas_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Completo'),
        ),
        migrations.AddField(
            model_name='personas',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido'),
        ),
    ]
