# Generated by Django 4.0.3 on 2022-03-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_personas_full_name_personas_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='habilidades',
            field=models.ManyToManyField(blank=True, null=True, to='personas.habilidades'),
        ),
    ]
