# Generated by Django 4.0.3 on 2022-03-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_alter_personas_habilidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='habilidades',
            field=models.ManyToManyField(blank=True, to='personas.habilidades'),
        ),
    ]
